@startuml
:Admin: as org

left to right direction

Rectangle "Admin" {
    (Display project list) as listPro
    Rectangle "Manage project" as manageP {
        (Create project) as createPro
        (Delete project) as deletePro
        (Duplicate project) as dupePro
        (Rename project) as renaPro
        Collections "Manage media" as manageM
    }
}


'Includes / extends

' Liens entre l'utilisateur (org) et les cas d'utilisation dans le package Admin
org--listPro
org--manageP
org--createPro
org--deletePro
org--dupePro
org--manageM
@enduml
