@startuml
'General diagram truncated for overall visibility. For more details, see the User and admin diagrams

:User: as usr
:Admin: as org
:Video platform: as vim <<Vimeo>>

left to right direction

Rectangle App {
    (Connect to webApp) as InAPP
    Collections User
    Collections Admin
}

org--Admin
org--InAPP: Enter webapp URL


usr--InAPP: Enter webapp URL
usr--InAPP: Scan QR code
usr--User

vim-up-User

'Includes / extends
@enduml
